version: '3.8'
x-all: &all-alias
  environment:
    - DISPLAY=${DISPLAY_ENV}
    - XAUTHORITY=${XAUTH_ENV}
    - NVIDIA_VISIBLE_DEVICES=all
  user: ${USER}
  stdin_open: true
  tty: true
  working_dir: /bpvol/${COMPOSE_PROJECT_NAME}
x-bld: &bld-alias
  cap_add:
    - SYS_PTRACE
  volumes:
    - .:/bpvol/${COMPOSE_PROJECT_NAME}
    - ..:/bpvol/workspace
    - /tmp/.X11-unix:/tmp/.X11-unix
    - /var/run/docker.sock:/var/run/docker.sock
    - ~/.ssh:/home/${USER}/.ssh
    - ~/.gitconfig:/home/${USER}/.gitconfig
    - /mnt/gitRepo:/mnt/gitRepo
x-all-build-args: &all-build-args-alias
  BPROTAG: ${BPROTAG}
  USERNAME: ${USER}
  USERID: ${USERID}
  GROUPID: ${GROUPID}
  DOCKGID: ${DOCKGID}
  TZ: ${TZ}
x-bld-build-args: &bld-build-args-alias
  WEBPRO: ${WEBPRO}
  INTERNPRO: ${INTERNPRO}
  PLUGINSDK: ${PLUGINSDK}
  CRTOOL: ${CRTOOL}
services:
  bld:
    <<: [*all-alias, *bld-alias]
    build:
      context: .devcontainer
      dockerfile: centos7-bld.dockerfile
      network: host
      args:
        <<: [*all-build-args-alias, *bld-build-args-alias]
        ADDSRC1: ${ADDSRC1}
        ADDSRC2: ${ADDSRC2}
    hostname: ${HNAME}
    network_mode: host
    profiles:
      - pbld
  gpu:
    <<: [*all-alias, *bld-alias]
    build:
      context: .devcontainer
      dockerfile: centos7-bld.dockerfile
      network: host
      args:
        <<: [*all-build-args-alias, *bld-build-args-alias]
        ADDSRC1: ${ADDSRC1}
        ADDSRC2: ${ADDSRC2}
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    hostname: ${HNAME}-gpu
    network_mode: host
    profiles:
      - pgpu
